### ISSUE TITLE
qBittorrent - 优秀的种子下载工具 | MoonlightWatch

### ISSUE THREAD

**Issue by moonlightwatch** [moonlightwatch/moonlightwatch.github.io#6]
https://blog.moonlightwatch.me/linux/2018/08/29/qBittorrent/ 

 今天在下载东西的时候，无意间发现了一款我个人认为非常优秀的下载工具。

**Comment by bainesing** [comment]
想玩一下，既然是webUI，那么元代码也是可以胡乱魔改的，有些跃跃欲试呢。
## 才不是RBQ（悄声bb）
